import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright

url = os.getenv('SITE_URL', 'http://127.0.0.1:4173/cqupt-zyfx/')
output = Path('test-results')
output.mkdir(exist_ok=True)
checks = []

def check(name, condition):
    assert condition, name
    checks.append(name)

def ready_photos(page):
    page.locator('img[data-media]').evaluate_all("images => images.forEach(image => image.loading = 'eager')")
    page.wait_for_function("[...document.querySelectorAll('img[data-media]')].every(i => i.complete && i.naturalWidth > 0)")
    for image in page.locator('img[data-media]:visible').all():
        image.scroll_into_view_if_needed()
        image.evaluate('(image) => image.decode()')
        page.wait_for_timeout(100)
    page.evaluate('window.scrollTo({top:0,behavior:"instant"})')
    page.wait_for_timeout(250)

with sync_playwright() as p:
    options = {'headless':True, 'args':['--no-sandbox']}
    if os.getenv('CHROMIUM_PATH'):
        options['executable_path'] = os.getenv('CHROMIUM_PATH')
    browser = p.chromium.launch(**options)
    page = browser.new_page(viewport={'width':1440,'height':1000},device_scale_factor=1)
    errors = []
    page.on('pageerror',lambda error:errors.append(str(error)))
    page.goto(url,wait_until='domcontentloaded')
    page.wait_for_function("document.documentElement.classList.contains('js')")
    check('home: association identity and desktop navigation',page.locator('h1').inner_text()=='跑步爱好者协会' and page.locator('#main-nav').is_visible())
    check('home: desktop has no overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    page.locator('[data-slide-step="-1"]').click()
    check('carousel: previous wraps to third photograph',page.locator('#slide-2').is_visible())
    page.locator('[data-slide-step="1"]').click()
    check('carousel: next wraps to first photograph',page.locator('#slide-0').is_visible())
    page.locator('[data-slide="1"]').click()
    check('carousel: direct selection updates accessible state',page.locator('[data-slide="1"]').get_attribute('aria-pressed')=='true')
    page.locator('[data-slide="0"]').click()
    page.locator('[data-gallery-filter="race"]').click()
    check('gallery: race filter shows four photographs',page.locator('.gallery-item:visible').count()==4)
    trigger=page.locator('.gallery-item:visible .photo-link').first
    trigger.click()
    check('gallery: photograph opens with attribution',page.locator('#photo-dialog').is_visible() and bool(page.locator('#photo-credit').inner_text()))
    old_title=page.locator('#photo-title').inner_text()
    page.keyboard.press('ArrowRight')
    check('gallery: keyboard next changes photograph',page.locator('#photo-title').inner_text()!=old_title)
    page.keyboard.press('Escape')
    check('gallery: Escape closes and restores focus',not page.locator('#photo-dialog').is_visible() and trigger.evaluate('(el)=>el===document.activeElement'))
    page.locator('[data-gallery-filter="campus"]').click()
    check('gallery: campus filter shows four photographs',page.locator('.gallery-item:visible').count()==4)
    page.locator('[data-gallery-filter="all"]').click()
    check('gallery: reset shows eight photographs',page.locator('.gallery-item:visible').count()==8)
    page.locator('[data-route="campus"]').click()
    check('routes: scene switch shows campus photograph',page.locator('#route-campus').is_visible() and not page.locator('#route-track').is_visible())
    page.locator('[data-route="track"]').click()
    page.locator('#pace-form button').click()
    check('pace: 5 km at 6:00 equals 30 minutes',page.locator('#pace-output').inner_text()=='00:30:00')
    page.locator('#distance').select_option('21.0975')
    page.locator('#pace-form button').click()
    check('pace: decimal race distance rounds correctly',page.locator('#pace-output').inner_text()=='02:06:35')
    page.locator('#pace-sec').fill('60')
    page.locator('#pace-form button').click()
    check('pace: invalid seconds show a useful error',page.locator('#pace-error').is_visible())
    page.locator('#pace-sec').fill('')
    page.locator('#pace-form button').click()
    check('pace: empty input cannot silently become zero',page.locator('#pace-error').is_visible())
    page.locator('#pace-sec').fill('0');page.locator('#distance').select_option('5');page.locator('#pace-form button').click()
    page.locator('[data-copy]').click()
    page.wait_for_function("document.querySelector('#copy-status').textContent.length>0")
    check('join: clipboard reports success or manual fallback',bool(page.locator('#copy-status').inner_text()))
    check('join: no unverified registration form',page.locator('form').count()==1 and page.locator('#join-button').get_attribute('data-copy') is not None)
    ready_photos(page)
    check('media: visible and hidden photos all decode locally',page.locator('img[data-media]').evaluate_all("ims=>ims.every(i=>i.naturalWidth>0&&new URL(i.currentSrc).origin===location.origin)"))
    page.locator('#gallery').scroll_into_view_if_needed()
    page.wait_for_timeout(300)
    page.screenshot(path=str(output/'gallery.png'))
    page.evaluate('window.scrollTo({top:0,behavior:"instant"})')
    page.wait_for_timeout(250)
    page.screenshot(path=str(output/'desktop.png'),full_page=True)
    page.screenshot(path=str(output/'desktop-top.png'))
    for width in [320,390,768,1024]:
        page.set_viewport_size({'width':width,'height':844})
        page.evaluate('window.scrollTo({top:0,behavior:"instant"})')
        check(f'{width}px: no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        if width<621:
            toggle=page.locator('.menu-toggle')
            check(f'{width}px: collapsed menu',toggle.is_visible() and not page.locator('#main-nav').is_visible())
            toggle.click()
            check(f'{width}px: expanded menu',page.locator('#main-nav').is_visible())
            page.keyboard.press('Escape')
            check(f'{width}px: Escape restores toggle focus',toggle.get_attribute('aria-expanded')=='false' and toggle.evaluate('(el)=>el===document.activeElement'))
        if width==390:
            ready_photos(page)
            page.screenshot(path=str(output/'mobile.png'),full_page=True)
    page.set_viewport_size({'width':1440,'height':1000})
    page.goto(url+'news.html',wait_until='domcontentloaded')
    check('news: three independently accessible articles',page.locator('.archive-item').count()==3)
    page.locator('[data-year-filter="2024"]').click()
    check('news: year filter works',page.locator('.archive-item:visible').count()==1)
    page.locator('.archive-item:visible h2 a').click()
    check('article: real page opens under project subpath',page.url.endswith('/news/marathon-2024.html') and page.locator('.article-source a').get_attribute('href').startswith('https://chongqing.eol.cn/'))
    page.reload(wait_until='domcontentloaded')
    ready_photos(page)
    check('article: direct refresh retains article and images',page.locator('h1').is_visible() and page.locator('.article-photo img').evaluate('(i)=>i.naturalWidth>0'))
    page.screenshot(path=str(output/'article.png'),full_page=True)
    page.goto(url+'sources.html',wait_until='domcontentloaded')
    check('sources: fourteen items have provenance and rights',page.locator('.source-photo').count()==14 and '署名并不等于授权' in page.locator('main').inner_text())
    page.goto(url+'notes/track-prep.html',wait_until='domcontentloaded')
    check('concurrent content: preparation note remains available',page.locator('h1').inner_text()=='田径场跑步准备' and '非重邮实拍' in page.locator('.article-photo').inner_text())
    check('JavaScript: no uncaught errors across pages',not errors)
    nojs=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844})
    fallback=nojs.new_page();fallback.goto(url,wait_until='domcontentloaded')
    check('no JS: navigation and articles remain accessible',fallback.locator('#main-nav').is_visible() and fallback.locator('h1').is_visible() and fallback.locator('.news-feature h3 a').is_visible())
    check('no JS: gallery source links remain available',fallback.locator('.photo-link').count()==8)
    check('no JS: mobile has no overflow',fallback.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    fallback.goto(url+'news/marathon-2025.html',wait_until='domcontentloaded')
    check('no JS: article body is real static HTML',fallback.locator('.article-body p').count()>=3)
    browser.close()

(output/'browser-checks.json').write_text(json.dumps({'passed':len(checks),'checks':checks},ensure_ascii=False,indent=2))
print(f'{len(checks)} browser checks passed')
