import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright

url=os.getenv('SITE_URL','http://127.0.0.1:4173/cqupt-zyfx/')
output=Path('test-results');output.mkdir(exist_ok=True)
checks=[]
def check(name,condition):
    assert condition,name
    checks.append(name)
def ready_photos(page):
    page.locator('img[data-media]').evaluate_all("images=>images.forEach(i=>i.loading='eager')")
    page.wait_for_function("[...document.querySelectorAll('img[data-media]')].every(i=>i.complete&&i.naturalWidth>0)")

with sync_playwright() as p:
    options={'headless':True,'args':['--no-sandbox']}
    if os.getenv('CHROMIUM_PATH'):options['executable_path']=os.getenv('CHROMIUM_PATH')
    browser=p.chromium.launch(**options)
    page=browser.new_page(viewport={'width':1440,'height':1000},reduced_motion='reduce')
    errors=[];page.on('pageerror',lambda error:errors.append(str(error)))
    page.goto(url,wait_until='networkidle')
    check('identity: association title and desktop navigation',page.locator('.club-name strong').inner_text()=='跑步爱好者协会' and page.locator('#main-nav').is_visible())
    check('desktop: no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    selectors=page.locator('[data-slide]')
    check('carousel: three manual selectors',selectors.count()==3)
    page.locator('[data-slide-step="-1"]').click()
    check('carousel: previous wraps to final slide',selectors.nth(2).get_attribute('aria-pressed')=='true')
    page.locator('[data-slide-step="1"]').click()
    check('carousel: next wraps to first slide',selectors.nth(0).get_attribute('aria-pressed')=='true')
    selectors.nth(1).click()
    check('carousel: direct selection updates state',selectors.nth(1).get_attribute('aria-pressed')=='true')
    page.locator('[data-gallery-filter="race"]').click()
    check('gallery: race filter shows four photographs',page.locator('.gallery-item:visible').count()==4)
    trigger=page.locator('.gallery-item:visible [data-photo]').first
    trigger.click()
    check('gallery: lightbox opens with attribution',page.locator('#photo-dialog').is_visible() and bool(page.locator('#photo-credit').inner_text()))
    old_title=page.locator('#photo-title').inner_text()
    page.keyboard.press('ArrowRight')
    check('gallery: keyboard next changes photograph',page.locator('#photo-title').inner_text()!=old_title)
    page.keyboard.press('Escape')
    check('gallery: Escape closes and restores focus',not page.locator('#photo-dialog').is_visible() and trigger.evaluate('(el)=>el===document.activeElement'))
    page.locator('[data-gallery-filter="campus"]').click()
    check('gallery: campus filter shows four photographs',page.locator('.gallery-item:visible').count()==4)
    page.locator('[data-gallery-filter="all"]').click()
    check('gallery: reset shows eight photographs',page.locator('.gallery-item:visible').count()==8)
    page.locator('[data-route="campus"]').click()
    check('routes: scene switch shows campus photograph',page.locator('#route-campus').is_visible() and not page.locator('#route-track').is_visible())
    page.locator('[data-route="track"]').click()
    page.locator('#pace-form button').click()
    check('pace: 5 km at 6:00 equals 30 minutes',page.locator('#pace-output').inner_text()=='00:30:00')
    page.locator('#distance').select_option('21.0975')
    page.locator('#pace-form button').click()
    check('pace: decimal race distance rounds correctly',page.locator('#pace-output').inner_text()=='02:06:35')
    page.locator('#pace-sec').fill('60')
    page.locator('#pace-form button').click()
    check('pace: invalid seconds show a useful error',page.locator('#pace-error').is_visible())
    page.locator('#pace-sec').fill('')
    page.locator('#pace-form button').click()
    check('pace: empty input cannot silently become zero',page.locator('#pace-error').is_visible())
    page.locator('#pace-sec').fill('0');page.locator('#distance').select_option('5');page.locator('#pace-form button').click()
    page.locator('.home-join-band [data-copy-group]').first.click()
    page.wait_for_function("document.querySelector('.home-join-band .join-copy-status').textContent.length>0")
    check('join: verified QQ group copy reports success or manual fallback','468686951' in page.locator('.home-join-band .join-copy-status').first.inner_text())
    check('join: no unverified registration form',page.locator('form').count()==1 and page.locator('.home-join-band form').count()==0 and page.locator('a[href="join.html"]').count()>0)
    ready_photos(page)
    check('media: visible and hidden photos all decode locally',page.locator('img[data-media]').evaluate_all("ims=>ims.every(i=>i.naturalWidth>0&&new URL(i.currentSrc).origin===location.origin)"))
    page.locator('#gallery').scroll_into_view_if_needed();page.wait_for_timeout(300);page.screenshot(path=str(output/'gallery.png'))
    page.evaluate('window.scrollTo({top:0,behavior:"instant"})');page.wait_for_timeout(250)
    page.screenshot(path=str(output/'desktop.png'),full_page=True);page.screenshot(path=str(output/'desktop-top.png'))
    for width in [320,390,768,1024]:
        page.set_viewport_size({'width':width,'height':844});page.evaluate('window.scrollTo({top:0,behavior:"instant"})')
        check(f'{width}px: no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        if width<621:
            page.locator('.menu-toggle').click()
            check(f'{width}px: mobile menu opens',page.locator('#main-nav').is_visible() and page.locator('.menu-toggle').get_attribute('aria-expanded')=='true')
            page.keyboard.press('Escape')
            check(f'{width}px: Escape closes menu',not page.locator('#main-nav').is_visible() and page.locator('.menu-toggle').get_attribute('aria-expanded')=='false')
    page.set_viewport_size({'width':390,'height':844});page.evaluate('window.scrollTo({top:0,behavior:"instant"})');page.wait_for_timeout(250)
    page.screenshot(path=str(output/'mobile.png'),full_page=True);page.screenshot(path=str(output/'mobile-top.png'))
    page.goto(url+'news.html',wait_until='networkidle')
    check('news: three archive articles',page.locator('.archive-item').count()==3)
    page.locator('[data-year-filter="2025"]').click()
    check('news: year filter leaves one article',page.locator('.archive-item:visible').count()==1)
    story_href=page.locator('.archive-item:visible .plain-link').get_attribute('href')
    check('news: article link is a real route',story_href.startswith('news/') and story_href.endswith('.html'))
    page.goto(url+story_href,wait_until='networkidle')
    check('article: direct refresh and image load',page.locator('.article-body').is_visible() and page.locator('.article-photo img').evaluate('(i)=>i.naturalWidth>0'))
    page.goto(url+'sources.html',wait_until='networkidle')
    check('sources: fourteen campus/source media entries',page.locator('.source-photo').count()==14)
    check('browser: no JavaScript page errors',not errors)
    nojs=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844})
    fallback=nojs.new_page();fallback.goto(url,wait_until='domcontentloaded')
    check('no JS: navigation and article links remain available',fallback.locator('#main-nav a').count()>=7 and fallback.locator('.news-row a').count()>=2)
    check('no JS: gallery retains source links',fallback.locator('.gallery-item .photo-link').count()==8)
    check('no JS: mobile has no horizontal overflow',fallback.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    fallback.goto(url+'news/marathon-2025.html',wait_until='domcontentloaded')
    check('no JS: static article body remains readable',fallback.locator('.article-body').is_visible())
    nojs.close();browser.close()

(output/'browser-checks.json').write_text(json.dumps({'passed':len(checks),'checks':checks},ensure_ascii=False,indent=2))
print(f'{len(checks)} browser checks passed')
