import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright

url = os.getenv('SITE_URL', 'http://127.0.0.1:4173/cqupt-zyfx/')
output = Path('test-results')
output.mkdir(exist_ok=True)
checks = []

def check(name, condition):
    assert condition, name
    checks.append(name)

def ready(page):
    page.locator('img[data-science-image]').evaluate_all("images=>images.forEach(i=>i.loading='eager')")
    page.wait_for_function("[...document.querySelectorAll('img[data-science-image]')].every(i=>i.complete&&i.naturalWidth>0)")
    page.evaluate('window.scrollTo({top:0,behavior:"instant"})')
    page.wait_for_timeout(150)

with sync_playwright() as p:
    options={'headless':True,'args':['--no-sandbox']}
    if os.getenv('CHROMIUM_PATH'): options['executable_path']=os.getenv('CHROMIUM_PATH')
    browser=p.chromium.launch(**options)
    page=browser.new_page(viewport={'width':1440,'height':1000},reduced_motion='reduce')
    errors=[]
    requests=[]
    page.on('pageerror',lambda error:errors.append(str(error)))
    page.on('request',lambda request:requests.append(request.url))
    page.goto(url+'science.html',wait_until='networkidle')
    check('science hub: six real chapter entries',page.locator('.sc-chapter').count()==6)
    check('science hub: active university navigation',page.locator('#main-nav [aria-current]').inner_text()=='科学跑步')
    check('science hub: initial reduced-motion load does not request GIFs',not any('.gif' in request for request in requests))
    check('science hub: 30 searchable static entries',page.locator('[data-resource]').count()==30)
    search=page.locator('#science-search')
    search.fill('发科莱特')
    check('science search: phonetic alias resolves Fartlek',page.locator('[data-resource]:visible').count()==2)
    search.fill('FARTLEK')
    page.locator('[data-science-filter="training"]').click()
    check('science search: case and category combined',page.locator('[data-resource]:visible').count()==1 and page.locator('[data-resource]:visible strong').inner_text()=='法特莱克')
    search.fill('not-a-running-topic')
    check('science search: empty state announced',page.locator('#science-empty').is_visible() and '0' in page.locator('#science-search-status').inner_text())
    page.locator('[data-clear-search]').click()
    check('science search: clear restores list and focus',page.locator('[data-resource]:visible').count()==30 and search.evaluate('(el)=>el===document.activeElement'))
    first=page.locator('[data-motion]').nth(0)
    second=page.locator('[data-motion]').nth(1)
    first.click()
    page.wait_for_function("document.querySelector('[data-motion]').getAttribute('aria-pressed')==='true'")
    first.locator('xpath=..').locator('xpath=..').locator('img').evaluate('(i)=>i.decode()')
    check('science motion: original GIF plays only on click',first.get_attribute('aria-pressed')=='true' and first.locator('xpath=..').locator('xpath=..').locator('img').get_attribute('src').endswith('.gif'))
    second.click()
    check('science motion: only one GIF plays at a time',page.locator('[data-motion][aria-pressed="true"]').count()==1 and first.get_attribute('aria-pressed')=='false')
    page.locator('[data-stop-motion]').click()
    check('science motion: stop all restores posters',page.locator('[data-motion][aria-pressed="true"]').count()==0 and '停止' in page.locator('#motion-status').inner_text())
    first.focus();page.keyboard.press('Enter')
    check('science motion: keyboard activation works',first.get_attribute('aria-pressed')=='true')
    page.keyboard.press('Enter')
    ready(page)
    page.screenshot(path=str(output/'science-desktop.png'),full_page=True)
    page.screenshot(path=str(output/'science-desktop-top.png'))
    for name in ['warm-up','stretching','training','strength','nutrition','recovery','references']:
        page.goto(url+'science/'+name+'.html',wait_until='networkidle')
        ready(page)
        check('science '+name+': direct route and real body',page.locator('h1').is_visible() and page.locator('.sc-section').count()>=3)
        check('science '+name+': no automatic GIF or external image',page.locator('img[data-science-image]').evaluate_all("ims=>ims.every(i=>new URL(i.src).origin===location.origin&&!i.src.endsWith('.gif'))"))
        for width in [320,390,768,1024,1440]:
            page.set_viewport_size({'width':width,'height':900})
            check(f'science {name}: {width}px no horizontal page overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        if name in ['training','strength','nutrition']:
            page.screenshot(path=str(output/('science-'+name+'.png')),full_page=True)
    page.goto(url+'science/nutrition.html',wait_until='networkidle')
    page.locator('#fuel-form button[type="submit"]').click()
    check('fuel: default example 45 g, 1.8 packets', '45 g' in page.locator('#fuel-output').inner_text() and '1.8 包' in page.locator('#fuel-output').inner_text())
    page.locator('#fuel-drink').fill('60');page.locator('#fuel-form button[type="submit"]').click()
    check('fuel: counts other carbohydrate without negative packets','剩余 0 g' in page.locator('#fuel-output').inner_text() and '多 15 g' in page.locator('#fuel-output').inner_text())
    page.locator('#fuel-hourly').fill('');page.locator('#fuel-form button[type="submit"]').click()
    check('fuel: blank rejected and stale result removed',page.locator('#fuel-error').is_visible() and not page.locator('#fuel-output').inner_text())
    page.locator('#fuel-hourly').fill('91');page.locator('#fuel-form button[type="submit"]').click()
    check('fuel: out of range rejected',page.locator('#fuel-error').is_visible())
    page.locator('#fuel-hourly').fill('90');page.locator('#fuel-duration').fill('30');page.locator('#fuel-drink').fill('0');page.locator('#fuel-form button[type="submit"]').click()
    check('fuel: short activity and high target cautions visible','高于 60' in page.locator('#fuel-output').inner_text() and '短时活动' in page.locator('#fuel-output').inner_text())
    page.goto(url+'science/strength.html',wait_until='networkidle')
    check('strength: ten exercises with original credits',page.locator('.sc-exercise').count()==10 and page.locator('.sc-media-credit').count()==10)
    check('strength: bridge and side plank correctly remain static pairs',page.locator('.sc-pair').count()==2)
    page.set_viewport_size({'width':390,'height':844});ready(page)
    page.screenshot(path=str(output/'science-strength-mobile.png'),full_page=True)
    page.goto(url+'science.html',wait_until='networkidle');ready(page)
    page.screenshot(path=str(output/'science-mobile.png'),full_page=True)
    page.screenshot(path=str(output/'science-mobile-top.png'))
    check('science mobile: no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.locator('.menu-toggle').click()
    check('science mobile: eight navigation links available',page.locator('#main-nav a:visible').count()==8)
    page.keyboard.press('Escape')
    check('science mobile: Escape closes menu',page.locator('.menu-toggle').get_attribute('aria-expanded')=='false')
    nojs=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844})
    fallback=nojs.new_page();fallback.goto(url+'science.html',wait_until='domcontentloaded')
    check('science no JS: all 30 resource links remain',fallback.locator('[data-resource]').count()==30 and not fallback.locator('#science-search').is_visible())
    fallback.goto(url+'science/strength.html',wait_until='domcontentloaded');ready(fallback)
    check('science no JS: movement posters and cues are readable',fallback.locator('.sc-exercise').count()==10 and not fallback.locator('[data-motion]').first.is_visible())
    fallback.goto(url+'science/nutrition.html',wait_until='domcontentloaded')
    check('science no JS: formula and tables remain without dead form',fallback.locator('.sc-formula').is_visible() and not fallback.locator('#fuel-form').is_visible())
    check('science: no uncaught JS errors',not errors)
    browser.close()

(output/'science-browser-checks.json').write_text(json.dumps({'passed':len(checks),'checks':checks},ensure_ascii=False,indent=2))
print(f'{len(checks)} scientific running browser checks passed')