import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import path from 'node:path';
import { renderSite } from './render.mjs';
import { buildMedia } from './media.mjs';
import { buildScienceMedia } from './science-media.mjs';
import { buildOfficialMedia } from './official-media.mjs';

const root = path.resolve(import.meta.dirname, '..');
const dist = path.join(root, 'dist');
const offline = process.argv.includes('--offline');
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await buildMedia({ offline });
await buildScienceMedia({ offline });
await buildOfficialMedia({ offline });
const content = JSON.parse(await readFile(path.join(root, 'data/content.json'), 'utf8'));
const media = JSON.parse(await readFile(path.join(dist, 'media/credits.json'), 'utf8'));
const pages = renderSite(content, media);
for (const [filename, html] of pages) {
  await mkdir(path.dirname(path.join(dist, filename)), { recursive: true });
  await writeFile(path.join(dist, filename), html);
}
await cp(path.join(root, 'assets'), path.join(dist, 'assets'), { recursive: true });
const { buildOfficialArchive } = await import('./official-build.mjs');
const officialPages = await buildOfficialArchive();
const { buildJoinExperience } = await import('./join-build.mjs');
const joinPages = await buildJoinExperience();
const { buildSiteStructure } = await import('./structure-build.mjs');
const structurePages = await buildSiteStructure();
const { buildClubCulture } = await import('./culture-build.mjs');
await buildClubCulture();
const { buildAssociationExperience } = await import('./association-build.mjs');
const associationPages = await buildAssociationExperience();
const { buildMotionExperience } = await import('./motion-build.mjs');
await buildMotionExperience();
const { finalizeAssociationExperience } = await import('./association-finalize.mjs');
await finalizeAssociationExperience();
const origin = 'https://yhan-sun.github.io/cqupt-zyfx/';
await writeFile(path.join(dist, '.nojekyll'), '');
await writeFile(path.join(dist, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${origin}sitemap.xml\n`);
const allPages = [...pages.keys(), ...officialPages, ...joinPages, ...structurePages, ...associationPages];
const locations = allPages.filter((file, index, all) => file !== '404.html' && all.indexOf(file) === index).map(file => `<url><loc>${origin}${file === 'index.html' ? '' : file}</loc></url>`).join('');
await writeFile(path.join(dist, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${locations}</urlset>\n`);
console.log(`Built ${new Set(allPages).size} pages with 20 self-flying official-account photographs, 9 supplied association photographs, culture-led event archive, 35-photo running gallery, standalone association story, motion-safe reveals, science hub and verified QQ join experience${offline ? ' from the offline source cache' : ''}.`);
