import { verifiedJoinUrl } from '../assets/core.mjs';

export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const external = 'target="_blank" rel="noopener noreferrer"';
const symbols = {
  people: '<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6m1 3a5 5 0 0 1 3 4v3"/>',
  calendar: '<rect x="3" y="5" width="18" height="16" rx="1"/><path d="M7 2v6m10-6v6M3 11h18m-13 4h2m4 0h2m-8 3h2"/>',
  pin: '<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',
  arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
  book: '<path d="M12 6c-3-3-7-3-10-2v15c4-1 7-1 10 2 3-3 6-3 10-2V4c-3-1-7-1-10 2Zm0 0v15"/>'
};
const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${symbols[name] || symbols.arrow}</svg>`;

export function renderSite(content, mediaList) {
  const e = escapeHtml;
  const media = Object.fromEntries(mediaList.map(item => [item.id, item]));
  const pages = new Map();
  const img = (id, {prefix = '', eager = false, className = '', alt = null, sizes = '100vw'} = {}) => {
    const item = media[id];
    if (!item) throw new Error(`Missing image ${id}`);
    const ext = item.format || 'webp';
    const srcset = item.smallWidth && item.smallWidth < item.width ? ` srcset="${prefix}media/${id}-small.${ext} ${item.smallWidth}w, ${prefix}media/${id}.${ext} ${item.width}w" sizes="${e(sizes)}"` : '';
    return `<img data-media="${id}" class="${className}" src="${prefix}media/${id}.${ext}"${srcset} width="${item.width || 800}" height="${item.height || 600}" alt="${e(alt ?? item.title)}" loading="${eager ? 'eager' : 'lazy'}" decoding="async"${eager ? ' fetchpriority="high"' : ''}>`;
  };
  const masthead = (prefix, active) => `<a class="skip-link" href="#main">跳到正文</a>
    <div class="utility"><div class="container"><span>重庆邮电大学学生社团</span><div><a href="https://www.cqupt.edu.cn/" ${external}>学校主页</a><a href="https://tyxy.cqupt.edu.cn/" ${external}>体育学院</a><a href="https://tuanwei.cqupt.edu.cn/" ${external}>校团委</a></div></div></div>
    <header class="masthead container"><a class="university-logo" href="https://www.cqupt.edu.cn/" ${external} aria-label="重庆邮电大学官网">${img('logo',{prefix,eager:true,alt:'重庆邮电大学'})}</a><a class="club-name" href="${prefix}./"><strong>跑步爱好者协会</strong><span>重邮约跑团 · 自邮飞翔</span></a><p class="school-motto">修德　博学　求实　创新<small>重庆邮电大学校训</small></p><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" hidden>菜单 <span aria-hidden="true">☰</span></button></header>
    <div class="nav-band"><nav id="main-nav" class="container" aria-label="主导航">${[['首页',prefix+'./','home'],['协会介绍',prefix+'./#about','about'],['校园赛事',prefix+'news.html','news'],['校园影像',prefix+'./#gallery','gallery'],['跑步服务',prefix+'./#running','running'],['加入我们',prefix+'./#join','join']].map(([label,url,key]) => `<a href="${url}"${active===key?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div>`;
  const footer = prefix => `<footer class="site-footer"><div class="container footer-main"><div><a href="${prefix}./" class="footer-title">重庆邮电大学跑步爱好者协会</a><p>重邮约跑团 · 自邮飞翔</p><p class="footer-address">重庆市南岸区崇文路2号 · 重庆邮电大学</p></div><div class="footer-links"><h2>校内链接</h2><a href="https://www.cqupt.edu.cn/" ${external}>重庆邮电大学</a><a href="https://tyxy.cqupt.edu.cn/" ${external}>体育学院</a><a href="https://tuanwei.cqupt.edu.cn/" ${external}>共青团重庆邮电大学委员会</a></div><div class="footer-links"><h2>网站导航</h2><a href="${prefix}news.html">赛事资料</a><a href="${prefix}sources.html">图片与资料来源</a><a href="https://github.com/yhan-sun/cqupt-zyfx" ${external}>网站代码</a></div></div><div class="container footer-bottom"><span>© 2026 自邮飞翔 · 社团展示网站</span><span>校园赛事为公开资料回顾，非当期招新或报名通知。</span><a href="#main">返回顶部 ↑</a></div></footer>`;
  const page = (filename, title, body, {active='home', prefix='', description='重庆邮电大学跑步爱好者协会，重邮约跑团 · 自邮飞翔。校园赛事资讯、跑步服务与社团参与指引。'}={}) => `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#108b96"><meta name="description" content="${e(description)}"><meta name="referrer" content="strict-origin-when-cross-origin"><meta property="og:type" content="website"><meta property="og:locale" content="zh_CN"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:image" content="https://yhan-sun.github.io/cqupt-zyfx/media/campus-pond.webp"><meta property="og:url" content="https://yhan-sun.github.io/cqupt-zyfx/${filename==='index.html'?'':filename}"><link rel="canonical" href="https://yhan-sun.github.io/cqupt-zyfx/${filename==='index.html'?'':filename}"><title>${e(title)}</title><link rel="icon" href="${prefix}assets/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}assets/styles.css"><script type="module" src="${prefix}assets/app.js"></script></head><body>${masthead(prefix,active)}${body}${footer(prefix)}</body></html>`;
  const newsRow = item => `<article class="news-row" data-year="${item.year}"><time datetime="${item.date}"><strong>${item.date.slice(8)}</strong><span>${item.date.slice(0,7).replace('-','.')}</span></time><div><a href="news/${item.id}.html"><h3>${e(item.title)}</h3></a><p>${e(item.summary)}</p><small>${e(item.sourceName)}</small></div></article>`;
  const feature = content.stories[1];
  const joinUrl = verifiedJoinUrl(content.join);
  const home = `<main id="main">
    <section class="hero" aria-label="校园与赛事图片" aria-roledescription="轮播图"><div class="slides">${content.slides.map((slide,index) => `<figure class="hero-slide" id="slide-${index}"${index ? ' hidden' : ''} aria-label="${index+1} / ${content.slides.length}">${img(slide.image,{eager:index===0,className:'hero-photo',alt:media[slide.image].title})}<figcaption><div class="container hero-inner"><p class="hero-kicker">${slide.kicker}</p>${index===0?'<h1>':'<h2>'}${slide.title}${index===0?'</h1>':'</h2>'}<p class="hero-subtitle">${slide.subtitle}</p><a class="hero-link" href="${slide.href}">${slide.label} ${icon('arrow')}</a><a class="hero-credit" href="sources.html#${slide.image}">${slide.note}</a></div></figcaption></figure>`).join('')}</div><div class="container hero-controls" hidden><button data-slide-step="-1" aria-label="上一张图片">‹</button><div class="slide-selectors" role="group" aria-label="选择首页图片">${content.slides.map((s,i)=>`<button data-slide="${i}" aria-label="第${i+1}张：${s.title}" aria-pressed="${i===0}">${String(i+1).padStart(2,'0')}</button>`).join('')}</div><button data-slide-step="1" aria-label="下一张图片">›</button></div><p id="slide-status" class="sr-only" role="status"></p></section>
    <div class="container quick-links" aria-label="快捷服务">${[['people','认识协会','#about','重邮约跑团 · 自邮飞翔'],['calendar','赛事回顾','news.html','历届校园马拉松资料'],['pin','跑步场地','#running','太极运动场与校园路跑'],['clock','配速换算','#pace','距离与用时计算']].map(([i,t,h,s])=>`<a href="${h}">${icon(i)}<span><strong>${t}</strong><small>${s}</small></span><span class="quick-arrow" aria-hidden="true">›</span></a>`).join('')}</div>
    <section class="container section news-section" id="news" aria-labelledby="news-title"><div class="news-main"><div class="section-heading"><h2 id="news-title">校园赛事</h2><a class="more" href="news.html">全部赛事 ${icon('arrow')}</a></div><div class="news-layout"><article class="news-feature"><a href="news/${feature.id}.html" class="image-link">${img(feature.image,{sizes:'(max-width: 700px) 100vw, 400px',alt:feature.imageNote})}<span class="photo-label">2025年比赛现场</span></a><div class="feature-body"><p class="meta"><time datetime="${feature.date}">${feature.date.replaceAll('-','.')}</time><span>校园马拉松</span></p><h3><a href="news/${feature.id}.html">${feature.title}</a></h3><p>${feature.summary}</p></div></article><div class="news-list">${content.stories.filter(item => item.id !== feature.id).map(newsRow).join('')}<a class="news-index-link" href="news.html">查看历届校园马拉松资料 ${icon('arrow')}</a></div></div></div><aside class="notice-column" aria-labelledby="notice-title"><div class="section-heading"><h2 id="notice-title">参与须知</h2></div><a href="#join" class="notice-item"><span class="notice-label">入团咨询</span><h3>想加入重邮约跑团？</h3><p>通过校内社团招新渠道，联系跑步爱好者协会。</p></a><a href="#faq" class="notice-item"><span class="notice-label">约跑准备</span><h3>出发前确认时间与集合点</h3><p>活动安排、天气与场地开放情况，以当期通知为准。</p></a><a href="https://tuanwei.cqupt.edu.cn/" class="campus-link" ${external}>校团委 · 校园活动 ${icon('arrow')}</a></aside></section>
    <section class="about-band" id="about" aria-labelledby="about-title"><div class="container about-layout"><figure class="about-image">${img('campus-gate',{sizes:'(max-width: 700px) 100vw, 600px'})}<figcaption>重庆邮电大学腾飞门 · Junyi Lou 摄 / 2019</figcaption></figure><div class="about-copy"><p class="section-overline">协会介绍</p><h2 id="about-title">重庆邮电大学<br>跑步爱好者协会</h2><p class="association-alias">重邮约跑团　/　自邮飞翔</p><p>这里汇集校园跑步资讯、场地资料与参与指引，方便重邮同学了解跑步活动、认识跑友。</p><p>无论是课后的操场慢跑，还是准备一场校园比赛，都可以从了解协会、确认活动安排开始。</p><div class="about-actions"><a class="button" href="#join">了解加入方式 ${icon('arrow')}</a><a class="plain-link" href="news.html">查看校园赛事</a></div></div></div></section>
    <section id="gallery" class="container section gallery-section" aria-labelledby="gallery-title"><div class="section-heading"><div><h2 id="gallery-title">校园影像</h2><p class="section-description">从校园风景到马拉松赛场，看看镜头里的重邮。</p></div><div class="filter-group" role="group" aria-label="筛选校园影像"><button data-gallery-filter="all" aria-pressed="true">全部</button><button data-gallery-filter="campus" aria-pressed="false">校园风光</button><button data-gallery-filter="race" aria-pressed="false">赛事现场</button></div></div><p class="sr-only" id="gallery-status" role="status"></p><div class="gallery-grid">${content.gallery.map(id => {const item=media[id];return `<figure class="gallery-item" data-category="${item.category}"><a class="photo-link" data-photo="${id}" href="${e(item.source)}" ${external} aria-label="查看图片：${item.title}">${img(id,{sizes:'(max-width: 600px) 50vw, 280px',alt:item.title+(item.year?'，'+item.year+'年':'，校园官网资料图')})}<span class="photo-zoom" aria-hidden="true">＋</span></a><figcaption><strong>${item.title}</strong><span>${item.year || '校园资料'}<a href="sources.html#${id}" aria-label="${item.title}的图片来源">来源</a></span></figcaption></figure>`;}).join('')}</div><p class="gallery-footnote">校园赛事照片不等同于协会活动照片。点击图片可查看大图及出处。</p></section>
    <section class="service-band" id="running" aria-labelledby="running-title"><div class="container section"><div class="section-heading"><h2 id="running-title">跑步服务</h2><span class="section-description">场地参考与配速换算</span></div><div class="services-layout"><div class="route-service"><div class="service-tabs" role="group" aria-label="选择跑步场景">${content.routes.map((r,i)=>`<button data-route="${r.id}" aria-pressed="${i===0}" aria-controls="route-${r.id}">${r.title}</button>`).join('')}</div>${content.routes.map((r,i)=>`<article id="route-${r.id}" class="route-panel"${i?' hidden':''}><figure>${img(r.image,{sizes:'(max-width: 700px) 100vw, 600px'})}<figcaption>${r.caption}</figcaption></figure><div class="route-copy"><h3>${r.title}</h3><p>${r.description}</p><p class="small-note">${r.note}</p><a class="plain-link" href="${e(r.map)}" ${external}>在地图中搜索 ${icon('arrow')}</a></div></article>`).join('')}<p id="route-live" class="sr-only" role="status"></p></div><section class="pace-box" id="pace" aria-labelledby="pace-title"><div class="pace-heading">${icon('clock')}<h3 id="pace-title">配速计算</h3></div><p class="pace-help">输入距离和每公里用时，换算匀速完成时间。</p><form id="pace-form"><label for="distance">跑步距离</label><select id="distance" name="distance"><option value="3">3 公里</option><option value="5" selected>5 公里</option><option value="10">10 公里</option><option value="21.0975">半程马拉松 · 21.0975 公里</option><option value="42.195">全程马拉松 · 42.195 公里</option></select><fieldset><legend>每公里配速</legend><div class="pace-fields"><label><span class="sr-only">配速分钟</span><input id="pace-min" type="number" min="0" max="30" step="1" value="6" required inputmode="numeric" aria-describedby="pace-error"><span>分</span></label><label><span class="sr-only">配速秒数</span><input id="pace-sec" type="number" min="0" max="59" step="1" value="0" required inputmode="numeric" aria-describedby="pace-error"><span>秒</span></label></div></fieldset><button type="submit" class="button">计算用时 ${icon('arrow')}</button><p id="pace-error" class="form-error" role="alert" hidden></p><div class="pace-result"><span>预计匀速用时</span><output id="pace-output" for="distance pace-min pace-sec" aria-live="polite">00:30:00</output></div></form><p class="small-note">仅作数学换算，不是成绩预测或训练建议。</p><noscript><p>计算方式：距离 × 每公里用时。互动换算需要启用 JavaScript。</p></noscript></section></div></div></section>
    <section class="container section join-section" id="join" aria-labelledby="join-title"><div class="join-panel"><p class="section-overline">加入我们</p><h2 id="join-title">联系跑步爱好者协会</h2><p>在校内社团招新渠道查找「重庆邮电大学跑步爱好者协会」，也可以使用「重邮约跑团」或「自邮飞翔」确认社团名称。</p><p>本学期招新时间、入群方式与日常约跑安排，请向社团确认。本站暂不收集报名信息。</p><div class="join-actions">${joinUrl?`<a id="join-button" class="button" href="${e(joinUrl)}" ${external}>${e(content.join.label)} ${icon('arrow')}</a>`:`<button id="join-button" class="button" type="button" data-copy="${e(content.name)}">复制社团名称 ${icon('people')}</button>`}<a class="plain-link" href="https://tuanwei.cqupt.edu.cn/" ${external}>查看校内社团活动</a></div><p id="copy-status" class="small-note" role="status"></p></div><div class="faq-list" id="faq"><h3>常见问题</h3><details><summary>刚开始跑步，可以参加吗？<span aria-hidden="true">＋</span></summary><p>参加前向组织者说明自己的跑步经验，了解活动距离、配速分组和收尾安排。按自己舒服的节奏参与，不勉强跟随更快的配速。</p></details><details><summary>在哪里集合，什么时候跑？<span aria-hidden="true">＋</span></summary><p>集合点与时间以当期社团通知为准。出发前确认天气和场地开放情况，遇到恶劣天气留意活动调整，不把往届赛事信息当作新的约跑安排。</p></details><details><summary>网站上的马拉松可以报名吗？<span aria-hidden="true">＋</span></summary><p>目前展示的是已举行的校园赛事资料，不是正在开放的报名项目。新赛事的报名条件、时间和入口，以学校或赛事主办方正式通知为准。</p></details><details><summary>如何补充活动照片或更正信息？<span aria-hidden="true">＋</span></summary><p>可通过网站仓库反馈资料出处。投稿照片前，请确认摄影和肖像使用授权；不要在公开反馈中提交手机号、学号或其他个人敏感信息。</p></details></div></section>
    <dialog class="photo-dialog" id="photo-dialog" aria-labelledby="photo-title"><div class="lightbox-toolbar"><span id="photo-position"></span><button class="dialog-close" aria-label="关闭图片">×</button></div><img id="lightbox-image" alt=""><div class="lightbox-info"><div><h2 id="photo-title"></h2><p id="photo-credit"></p><a id="photo-source" ${external}>查看原始出处 ↗</a></div><div class="lightbox-arrows"><button data-photo-step="-1" aria-label="上一张照片">‹</button><button data-photo-step="1" aria-label="下一张照片">›</button></div></div></dialog><script type="application/json" id="gallery-data">${JSON.stringify(content.gallery.map(id=>({...media[id],src:`media/${id}.${media[id].format}`}))).replaceAll('<','\\u003c')}</script>
  </main>`;
  pages.set('index.html',page('index.html','重庆邮电大学跑步爱好者协会｜重邮约跑团 · 自邮飞翔',home));
  const breadcrumbs = title => `<div class="breadcrumbs container"><a href="./">首页</a><span> / </span><span>${title}</span></div>`;
  pages.set('news.html',page('news.html','校园赛事｜重庆邮电大学跑步爱好者协会',`<main id="main">${breadcrumbs('校园赛事')}<section class="container section archive"><div class="page-heading"><h1>校园赛事</h1><p>重邮人马拉松历届公开资料。按赛事日期由近到远排列。</p></div><div class="archive-toolbar"><div class="filter-group" role="group" aria-label="筛选赛事年份">${['all','2026','2025','2024'].map((y,i)=>`<button data-year-filter="${y}" aria-pressed="${i===0}">${y==='all'?'全部年份':y+'年'}</button>`).join('')}</div><span id="news-status" role="status">共 ${content.stories.length} 篇</span></div><div class="archive-list">${content.stories.map(item=>`<article class="archive-item" data-year="${item.year}"><a href="news/${item.id}.html" class="image-link">${img(item.image,{sizes:'(max-width: 620px) 100vw, 300px',alt:item.imageNote})}<span class="photo-label">${item.imageNote}</span></a><div><p class="meta">${item.date.replaceAll('-','.')}　/　${e(item.sourceName)}</p><h2><a href="news/${item.id}.html">${item.title}</a></h2><p>${item.summary}</p><a href="news/${item.id}.html" class="plain-link">阅读全文 ${icon('arrow')}</a></div></article>`).join('')}</div></section></main>`,{active:'news'}));
  for (const item of content.stories) {
    const others=content.stories.filter(x=>x.id!==item.id);
    pages.set(`news/${item.id}.html`,page(`news/${item.id}.html`,`${item.title}｜校园赛事`,`<main id="main"><div class="breadcrumbs container"><a href=".././">首页</a><span> / </span><a href="../news.html">校园赛事</a><span> / 正文</span></div><article class="article-page container"><header><p class="section-overline">校园马拉松 · 赛事回顾</p><h1>${item.title}</h1><p class="article-meta">赛事日期：<time datetime="${item.date}">${item.date}</time><span>资料来源：${e(item.sourceName)}</span></p></header><figure class="article-photo">${img(item.image,{prefix:'../',eager:true,sizes:'(max-width: 800px) 100vw, 800px',alt:item.imageNote})}<figcaption>${item.imageNote} · ${e(media[item.image].credit)}</figcaption></figure><div class="article-body">${item.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}<p class="article-source"><a href="${e(item.source)}" ${external}>阅读原始报道 ↗</a><span>本站整理，不是当期报名通知。</span></p></div><div class="related-news"><h2>更多赛事资料</h2>${others.map(x=>`<a href="${x.id}.html">${x.title}<span>${x.year}</span></a>`).join('')}</div></article></main>`,{active:'news',prefix:'../',description:item.summary}));
  }
  pages.set('sources.html',page('sources.html','图片与资料来源｜重邮约跑团',`<main id="main">${breadcrumbs('图片与资料来源')}<article class="container source-page section"><div class="page-heading"><h1>图片与资料来源</h1><p>资料查阅日期：${content.updated}。图片保留作者、供稿方与原文入口。</p></div><section><h2>设计参考</h2><p>本版参考<a href="https://www.cqupt.edu.cn/" ${external}>重庆邮电大学现版官网</a>的青绿色、通栏校园摄影、中文导航和日期新闻列表。官网样式中的主色为 #108B96，辅助色为 #F4CA91；本站对文字与交互控件使用更深的青色，以改善对比度。没有复制官网代码或字体文件。</p><p>页首学校标识来自官网，仅用于学校识别，并链接回学校主页，不作为协会自有会徽或学校对本站的认证标记。本站是委托建设的社团展示站，不是学校行政门户。</p></section><section><h2>赛事资料</h2>${content.stories.map(s=>`<div class="source-entry"><h3><a href="${e(s.source)}" ${external}>${s.title} ↗</a></h3><p>${s.date} · ${e(s.sourceName)}</p></div>`).join('')}<p>名称“重庆邮电大学跑步爱好者协会”“重邮约跑团”“自邮飞翔”由委托方提供。未独立核实的成立时间、成员人数、训练课表、入群二维码与负责人联系方式不发布。校园赛事不等同于协会主办赛事。</p></section><section><h2>图片清单</h2><p>官网及新闻供图未发现开放许可，版权仍归原作者或相关单位。本版作为社团网站设计与资料展示使用，不宣称已取得转载授权；正式运营前，运营方应向权利人确认使用范围，或换成协会已获授权的照片。署名并不等于授权。</p><p>腾飞门照片采用 CC BY-SA 4.0，本版缩放、转码和版式裁切版本继续遵循该许可。其余图片不适用该开放许可。</p><div class="source-photos">${mediaList.map(m=>`<div class="source-photo" id="${m.id}">${img(m.id,{sizes:'140px',alt:m.title})}<div><h3>${e(m.title)}${m.year?' · '+m.year:''}</h3><p>${e(m.credit)}</p><p>${e(m.license)}</p><a href="${e(m.source)}" ${external}>原始出处 ↗</a>${m.licenseUrl?` · <a href="${e(m.licenseUrl)}" ${external}>许可协议 ↗</a>`:''}</div></div>`).join('')}</div></section><section><h2>使用与隐私说明</h2><p>照片在构建时下载、验证并压缩为同站资源。访客浏览本站不需要请求外部图库；点击外链后适用目标网站的规则。网站没有账号或报名后台，不收集报名资料，不含广告和统计脚本。托管方可能保留基础访问日志。</p><p>配速计算只在浏览器进行；复制按钮仅在点击时写入社团名称，不读取剪贴板。图片页和赛事正文无需 JavaScript 也可访问。</p><p>图片或内容更正请通过<a href="https://github.com/yhan-sun/cqupt-zyfx/issues" ${external}>网站仓库</a>反馈。请勿在公开 Issue 中填写个人联系方式或报名资料。</p></section></article></main>`,{active:'sources'}));
  pages.set('404.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>页面未找到｜重邮约跑团</title><style>body{margin:0;font-family:system-ui,sans-serif;color:#16484d;background:#f1f7f7;min-height:100vh;display:grid;place-items:center}main{padding:30px;max-width:500px}h1{font-size:32px}p{line-height:1.9}a{display:inline-block;padding:12px 24px;background:#087780;color:white;text-decoration:none}a:focus-visible{outline:3px solid #16484d;outline-offset:5px}</style><main><p>重庆邮电大学跑步爱好者协会</p><h1>页面未找到</h1><p>当前地址可能已更改，请返回首页查找校园赛事或社团信息。</p><a href="/cqupt-zyfx/">返回首页</a></main></html>`);
  return pages;
}
