import { renderScience } from './science.mjs';
import { page, image, photoLink, breadcrumbs, pageHeading, external, localHref, escapeHtml as e, arrow } from './layout.mjs';

export { escapeHtml } from './layout.mjs';

export function renderSite(model) {
  const { site, join, members, runners, photos, profilePhotos = [], posts, content, media, gallery, official } = model;
  const pages = new Map();
  const photoById = new Map([...photos, ...profilePhotos].map(item => [item.id, item]));
  const postById = new Map(posts.map(item => [item.id, item]));
  const baseImage = id => {
    const item = media.find(item => item.id === id);
    if (!item) throw new Error(`Unknown source image: ${id}`);
    const extension = item.format || 'webp';
    return { ...item, src: `media/${id}.${extension}`, variants: item.smallWidth ? [
      { src: `media/${id}-small.${extension}`, width: item.smallWidth },
      { src: `media/${id}.${extension}`, width: item.width }
    ] : [] };
  };
  const add = (path, title, body, options) => pages.set(path, page(path, title, body, options));
  const sourceLink = (item, prefix = '') => `<a href="${e(localHref(item.source, prefix))}"${item.source.startsWith('https:') ? ' ' + external : ''}>${e(item.sourceLabel || item.credit || '来源')} ↗</a>`;
  const caption = (photo, prefix = '') => `<figcaption>${e(photo.title)}<span>${e(photo.dateLabel)} · ${sourceLink(photo, prefix)}</span></figcaption>`;
  const figure = (id, options = {}) => {
    const photo = photoById.get(id);
    return `<figure>${photoLink(photo, options)}${caption(photo, options.prefix)}</figure>`;
  };
  const postRow = post => `<article class="activity-row" id="${e(post.id)}"><a class="activity-cover" href="${post.path}">${image(post.photos[0])}</a><div><p class="meta"><time datetime="${post.date}">${e(post.dateLabel)}</time><span>${e(post.relationship)}</span></p><h3><a href="${post.path}">${e(post.title)}</a></h3><p>${e(post.summary)}</p><a class="text-link" href="${post.path}">查看记录 ${arrow}</a></div></article>`;
  const joinStrip = () => `<section class="join-strip container"><div><h2>加入重邮约跑团</h2><p>QQ 群 ${e(join.groupNumber)}，活动安排见群内通知。</p></div><a class="button" href="join.html">查看加入方式 ${arrow}</a></section>`;
  const sectionTitle = (title, href, label) => `<div class="section-heading"><h2>${title}</h2><a href="${href}">${label} ${arrow}</a></div>`;
  const runnerRecordList = profile => profile.records.map(record => `<div class="runner-record"><dt>${e(record.label)}</dt><dd>${e(record.value)}</dd></div>`).join('');
  const runnerCard = (profile, index) => {
    const photo = photoById.get(profile.image);
    return `<article class="runner-profile-card" id="runner-${e(profile.id)}" data-runner-profile="${e(profile.id)}"><figure class="runner-profile-photo">${photoLink(photo, { eager: index === 0, sizes: '(max-width: 700px) 100vw, (max-width: 1000px) 50vw, 560px' })}<figcaption><span>${String(index + 1).padStart(2, '0')}</span><span>照片由本人提供</span></figcaption></figure><div class="runner-profile-body"><header class="runner-profile-header"><h2>${e(profile.name)}</h2><p class="runner-profile-identity"><span>${e(profile.grade)}</span><span>${e(profile.college)}</span></p></header><dl class="runner-records" aria-label="${e(profile.name)}的跑步记录">${runnerRecordList(profile)}</dl><div class="runner-motto"><span>个人宣言</span><blockquote>“${e(profile.motto)}”</blockquote></div></div></article>`;
  };
  const runnerDescription = '跑友风采：查看重邮跑步爱好者协会跑友的本人资料、跑步记录、个人宣言与真实校园跑步照片。';
  const firstRunner = runners.items[0];
  const firstRunnerPhoto = photoById.get(firstRunner.image);
  const runnerHomeTeaser = `<section class="runner-home-teaser" id="runners-preview"><div class="container runner-home-teaser-grid"><div class="runner-home-teaser-copy"><p class="section-overline">跑友风采</p><h2>认识跑友</h2><p>从校园跑道上的一张照片开始，看看跑友如何记录自己的距离、时间和坚持。</p><a class="plain-link" href="runners.html">查看跑友风采 ${arrow}</a></div><div class="runner-home-profile"><figure>${photoLink(firstRunnerPhoto, { sizes: '(max-width: 850px) 100vw, 560px' })}<figcaption>01 · 跑步人物</figcaption></figure><div><span>${e(firstRunner.grade)} · ${e(firstRunner.college)}</span><strong>${e(firstRunner.name)}</strong><a class="text-link" href="runners.html#runner-${e(firstRunner.id)}">查看个人资料 ${arrow}</a></div></div></div></section>`;

  const hero = photoById.get(site.homePhoto);
  add('index.html', '首页', `<main id="main"><section class="home-hero container"><div class="hero-picture">${image(hero, { eager: true, sizes: '(max-width: 1200px) 100vw, 1200px' })}<div class="hero-copy"><p>重庆邮电大学跑步爱好者协会</p><h1>重邮约跑团</h1><p class="hero-description">日常约跑、训练交流、赛事同行。</p><div class="actions"><a class="button" href="join.html">加入我们 ${arrow}</a><a class="hero-link" href="about.html">协会介绍</a></div></div></div><p class="hero-caption">${e(hero.title)} · ${e(hero.dateLabel)} · ${sourceLink(hero)}</p></section><section class="container section" id="activities">${sectionTitle('活动记录', 'club.html', '全部记录')}<div class="home-activities">${site.featuredPosts.map(id => postRow(postById.get(id))).join('')}</div></section><section class="photo-section" id="gallery"><div class="container section">${sectionTitle('跑步日常', 'gallery.html', '进入相册')}<div class="photo-teasers">${site.homePhotos.map(id => figure(id)).join('')}</div></div></section>${runnerHomeTeaser}<section class="container section" id="science">${sectionTitle('跑步指南', 'science.html', '全部专题')}<div class="guide-links"><a href="science/warm-up.html"><h3>跑前热身</h3><p>热身顺序与动作示范</p></a><a href="science/training.html"><h3>训练方法</h3><p>轻松跑、节奏跑、间歇与法特莱克</p></a><a href="science/nutrition.html"><h3>营养与补给</h3><p>日常饮食、长距离碳水与补液</p></a></div></section>${joinStrip()}</main>`, { active: 'home' });

  add('about.html', '协会介绍', `<main id="main">${breadcrumbs('协会介绍')}<div class="container">${pageHeading('协会介绍', site.alias)}<section class="about-intro" id="identity"><div class="prose"><h2>${e(site.name)}</h2><p>${e(site.intro)}</p><p>日常交流通过「重邮约跑团」QQ 群进行，活动和参赛文章可在「CQUPT自邮飞翔」公众号查阅。</p><p><a class="text-link" href="join.html">加入跑团 ${arrow}</a></p></div>${figure('member-two-runners', { eager: true, sizes: '(max-width: 800px) 100vw, 560px' })}</section><section class="section routine"><h2>日常活动</h2><dl>${site.routine.map(item => `<div><dt>${e(item.title)}</dt><dd>${e(item.text)}</dd></div>`).join('')}</dl></section><section class="captain-story section"><div>${figure('member-captain-run', { sizes: '(max-width: 700px) 100vw, 380px' })}</div><div class="prose"><h2>会长自述</h2><p class="meta">${e(members.captain.name)} · ${e(members.captain.grade)} · ${e(members.captain.role)}</p><blockquote>${members.captain.story.map(text => `<p>${e(text)}</p>`).join('')}</blockquote><p class="small">文字由本人提供。</p></div></section><p class="small" id="member-media">训练和赛事照片见<a href="gallery.html">相册</a>；图片使用说明见<a href="sources.html#association-supplied-media" id="media-note">来源页</a>。</p></div>${joinStrip()}</main>`, { active: 'about', description: site.intro, shareImage: photoById.get('member-two-runners').src });

  const years = [...new Set(posts.map(post => post.year))];
  const campusRows = content.stories.map(story => `<article class="campus-row"><time datetime="${story.date}">${story.date}</time><div><h3><a href="news/${story.id}.html">${e(story.title)}</a></h3><p>${e(story.summary)}</p><small>${e(story.sourceName)}</small></div></article>`).join('');
  add('club.html', '活动记录', `<main id="main">${breadcrumbs('活动记录')}<div class="container">${pageHeading('活动记录', '校园训练和跑团参赛，按年份查阅。')}<nav class="year-nav" aria-label="按年份查阅">${years.map(year => `<a href="#year-${year}">${year}</a>`).join('')}<a href="#campus-events">校园赛事</a></nav>${years.map(year => `<section class="year-section" id="year-${year}" aria-labelledby="year-title-${year}"><h2 id="year-title-${year}">${year}</h2><div>${posts.filter(post => post.year === year).map(postRow).join('')}</div></section>`).join('')}<section class="campus-events section" id="campus-events"><h2>相关校园赛事</h2><p class="section-description">重邮人马拉松的历届报道。以下为学校赛事，不表示由协会主办。</p>${campusRows}</section></div></main>`, { active: 'events', description: '重邮跑团的校园训练、马拉松与高校联赛记录，以及历届重邮人马拉松报道。' });

  for (const post of posts) {
    const historical = post.id === 'recruit-2025';
    const training = official.historicalTraining;
    const history = historical ? `<aside class="notice">这是 2025 年招新记录，不是当前招新通知。<a href="../join.html">当前加入方式</a></aside><details class="history-details" id="training-history"><summary>2025 年文章中的训练安排</summary><p>以下是不代表当前训练时间的历史资料。</p><dl>${training.items.map(item => `<div><dt>${e(item.day)} ${e(item.time)}</dt><dd>${e(item.type)}：${e(item.detail)}</dd></div>`).join('')}</dl><p>${e(training.place)}</p></details>` : '';
    const facts = post.facts.filter(fact => !historical || !fact.value.includes('周六'));
    const caveat = post.id === 'relay-2024' ? '原文的“首次出征”指马拉松战队的该次参赛，不是协会成立时间。' : post.id === 'night-run-2024' ? '团队报名奖与比赛竞技名次不同。' : '';
    add(post.path, post.title, `<main id="main">${breadcrumbs('活动记录', '../')}<article class="container article"><header class="article-header"><p class="meta">${e(post.relationship)} · ${post.eventDate ? `<time datetime="${post.eventDate}">${post.eventDate}</time>` : '活动日期未单独登记'}</p><h1>${e(post.title)}</h1><p class="small">${e(official.sourceName)} · ${post.published} 发布 · <a href="${e(post.source)}" ${external}>公众号原文 ↗</a></p></header>${history}<div class="prose"><p class="article-lead">${e(post.summary)}</p><dl class="fact-list">${facts.map(fact => `<div><dt>${e(fact.label)}</dt><dd>${e(fact.value)}</dd></div>`).join('')}</dl>${caveat ? `<p class="small">${caveat}</p>` : ''}</div><section class="article-photos" aria-label="活动照片">${post.photos.map(photo => figure(photo.id, { prefix: '../', sizes: '(max-width: 800px) 100vw, 800px' })).join('')}</section><p class="small">原文：<a href="${e(post.source)}" ${external}>${e(post.originalTitle)} ↗</a></p><a class="text-link" href="../club.html#${post.id}">← 返回活动记录</a></article></main>`, { active: 'events', description: post.summary, shareImage: post.photos[0].src });
  }

  const galleryCard = photo => `<figure class="gallery-card" data-gallery-item data-category="${photo.category}">${photoLink(photo)}<figcaption><strong>${e(photo.title)}</strong><span>${e(photo.dateLabel)} · ${e(photo.scope)}</span>${sourceLink(photo)}</figcaption></figure>`;
  add('gallery.html', '相册', `<main id="main">${breadcrumbs('相册')}<div class="container">${pageHeading('相册', '日常训练和参赛记录。')}<div class="gallery-filters" role="group" aria-label="筛选照片" hidden><button type="button" data-gallery-filter="all" aria-pressed="true">全部</button>${Object.entries(gallery.categories).map(([key, label]) => `<button type="button" data-gallery-filter="${key}" aria-pressed="false">${label}</button>`).join('')}<span id="gallery-status" role="status" aria-live="polite"></span></div><div class="gallery-grid">${photos.map(galleryCard).join('')}</div><p class="small gallery-note">图片版权归原权利人；转载请另行取得许可。<a href="sources.html">图片来源与使用说明</a></p></div></main>`, { active: 'gallery', description: '重邮跑团的日常训练和参赛记录。学校代表队与校园赛事照片分别注明。' });

  add('runners.html', '跑友风采', `<main id="main" class="runner-page">${breadcrumbs('跑友风采')}<header class="runner-hero"><div class="container runner-hero-grid"><div class="runner-hero-copy"><h1>跑友风采</h1></div></div></header><section class="container runner-directory" aria-label="跑友资料"><div class="runner-profile-grid">${runners.items.map(runnerCard).join('')}</div></section></main>`, { active: 'runners', description: runnerDescription, shareImage: firstRunnerPhoto.src });

  add('join.html', '加入我们', `<main id="main">${breadcrumbs('加入我们')}<div class="container join-page">${pageHeading('加入重邮约跑团')}<section class="join-main" aria-label="QQ 加群"><div class="join-copy"><p>${e(join.purpose)}。新手和有训练基础的跑友都欢迎。</p><p class="group-label">QQ 群号</p><p class="group-number" id="group-number">${e(join.groupNumber)}</p><div class="actions"><a class="button" href="${e(join.joinUrl)}" ${external}>打开 QQ 加群 ↗</a><button type="button" class="button secondary" data-copy-group="${e(join.groupNumber)}" hidden>复制群号</button></div><p class="small" id="copy-status" role="status">也可以在 QQ 中搜索群号申请加入。</p><p>活动时间、集合点和分组以群内当期通知为准。</p></div><figure class="join-qr"><img src="${e(join.qrImage)}" width="220" height="220" alt="重邮约跑团 QQ 加群二维码"><figcaption>使用 QQ 扫码加入</figcaption></figure></section><section class="join-questions"><h2>入群前了解</h2><details><summary>刚开始跑步，可以参加吗？</summary><p>可以先入群了解活动。参加前说明自己的经验，确认距离和分组，选择适合自己的节奏。</p></details><details><summary>什么时候、在哪里集合？</summary><p>请查看群公告和当期活动通知，出发前确认天气及场地安排。本站的历史记录不是当前课表。</p></details><details><summary>网站可以报名比赛吗？</summary><p>本站不办理赛事报名。参赛资格、费用和报名入口以主办方通知为准。</p></details><p class="small">${e(join.audience)}</p></section></div></main>`, { active: 'join', description: `重邮约跑团 QQ 群 ${join.groupNumber}。扫码、打开 QQ 链接或搜索群号申请加入。` });

  for (const story of content.stories) {
    const photo = baseImage(story.image);
    add(`news/${story.id}.html`, story.title, `<main id="main">${breadcrumbs('校园赛事', '../')}<article class="container article"><header class="article-header"><p class="meta">校园赛事 · <time datetime="${story.date}">${story.date}</time></p><h1>${e(story.title)}</h1><p class="small">${e(story.sourceName)} · <a href="${e(story.source)}" ${external}>原始报道 ↗</a></p></header><figure class="article-photo">${image(photo, { prefix: '../', eager: true, sizes: '(max-width: 800px) 100vw, 800px' })}<figcaption>${e(story.imageNote)}</figcaption></figure><div class="prose">${story.paragraphs.map(text => `<p>${e(text)}</p>`).join('')}</div><p class="small">学校赛事资料，不代表协会主办。</p><a class="text-link" href="../club.html#campus-events">← 返回校园赛事</a></article></main>`, { active: 'events', description: story.summary, shareImage: photo.src });
  }
  add('news.html', '校园赛事', `<main id="main">${breadcrumbs('校园赛事')}<div class="container">${pageHeading('校园赛事', '重邮人马拉松历届报道。')}<p><a class="text-link" href="club.html#campus-events">前往活动记录 ${arrow}</a></p><section class="section">${campusRows}</section></div></main>`, { active: 'events', noindex: true });

  for (const note of content.notes) {
    add(`notes/${note.id}.html`, note.title, `<main id="main">${breadcrumbs('跑步指南', '../')}<article class="container article"><header class="article-header"><p class="meta">社团来稿 · ${note.date}</p><h1>${e(note.title)}</h1></header><figure>${image(baseImage(note.image), { prefix: '../', sizes: '(max-width: 800px) 100vw, 800px' })}<figcaption>${e(note.imageNote)} · <a href="../sources.html#track">来源与许可</a></figcaption></figure><div class="prose">${note.paragraphs.map(text => `<p>${e(text)}</p>`).join('')}</div><p><a href="${e(note.source)}" ${external}>来稿记录 ↗</a></p><a href="../science.html">← 返回跑步指南</a></article></main>`, { active: 'science', description: '集体约跑前，确认集合位置、场地安排与参与节奏。' });
  }

  const mediaEntry = item => `<li id="${e(item.id)}"><h3>${e(item.title)}</h3><p>${e(item.credit || item.sourceLabel || '协会提供')} · ${e(item.year || item.published || '')}</p><p>${e(item.license || members.rights)}</p><a href="${e(item.article || item.source || item.evidence || 'gallery.html')}" ${(item.article || item.source || item.evidence || '').startsWith('https:') ? external : ''}>${item.article ? '公众号原文' : item.source || item.evidence ? '原始资料' : '查看照片'} ↗</a>${item.licenseUrl ? ` · <a href="${e(item.licenseUrl)}" ${external}>许可说明 ↗</a>` : ''}</li>`;
  const runnerSourceRows = runners.items.map(profile => {
    const photo = photoById.get(profile.image);
    const photoSource = photo ? `照片：${e(photo.title)} · ${e(photo.sourceLabel || profile.source)}。` : '';
    return `<li id="runner-source-${e(profile.id)}"><h3>${e(profile.name)}的跑友资料</h3><p>个人资料、跑步记录与照片 · ${e(profile.source)} · ${e(runners.reviewedAt)}</p><p>${e(profile.note)} ${e(runners.rights)} ${photoSource}</p><a href="runners.html#runner-${e(profile.id)}">查看跑友风采 ↗</a></li>`;
  }).join('');
  add('sources.html', '资料与图片来源', `<main id="main">${breadcrumbs('资料与图片来源')}<article class="container sources-page">${pageHeading('资料与图片来源')}<div class="prose"><p>活动摘要保留原文链接。协会提供的照片、公众号图片、跑友资料和学校赛事资料分别登记；图片署名并不等于授权。</p><p>本站没有报名后台，不收集学号、手机号或个人报名资料。如需更正内容或下架图片，请通过<a href="https://github.com/yhan-sun/cqupt-zyfx/issues" ${external}>网站反馈</a>或联系跑团管理员。请勿在公开反馈中提交敏感信息。</p></div><section class="section" id="association-supplied-media"><h2>协会提供的照片</h2><p>${e(members.rights)}</p><p>学校代表队比赛照片不作为协会团体成绩。会长自述由本人提供。</p><ul class="source-list">${members.items.map(item => mediaEntry({ ...item, source: null, credit: '协会提供' })).join('')}</ul></section><section class="section" id="runner-profiles"><h2>跑友风采资料</h2><p>人物资料与照片仅在本人确认的展示范围内使用；成绩由本人提供，不构成协会或学校的排名。</p><ul class="source-list">${runnerSourceRows}</ul></section><section class="section" id="official-wechat"><h2>公众号活动记录与图片</h2><p>来源：${e(official.sourceName)}。仅整理活动摘要，不转载个人成绩表；公众号图片未发现开放许可。</p><ul class="source-posts">${posts.map(post => `<li><time>${post.published}</time><a href="${e(post.source)}" ${external}>${e(post.originalTitle)} ↗</a></li>`).join('')}</ul><details><summary>逐张查看公众号图片来源</summary><ul class="source-list">${photos.filter(item => item.kind === 'official').map(mediaEntry).join('')}</ul></details></section><section class="section" id="campus-media"><h2>校园与赛事资料</h2><p>校园赛事由学校或赛事主办方组织。2026 年重邮人马拉松所用配图为校园资料图，不是该届比赛现场。</p><ul class="source-list">${media.map(mediaEntry).join('')}</ul></section><section class="section"><h2>跑步指南</h2><p>动作图源、许可和文字参考资料单独列出。</p><a href="science/references.html">跑步指南参考资料 ${arrow}</a></section></article></main>`, { description: '活动原文、照片署名、人物资料、使用范围与更正方式。' });
  add('404.html', '页面未找到', `<main id="main" class="container error-page"><p class="meta">404</p><h1>页面未找到</h1><p>链接可能已经变更，可以从首页继续查找。</p><a class="button" href="${site.origin}">返回首页</a></main>`, { noindex: true });

  for (const [path, html] of renderScience({ page, e, img: () => '', icon: () => arrow })) pages.set(path, html);
  return pages;
}
